M48
; DRILL file {KiCad 7.0.8} date Wed 04 Oct 2023 18:10:47
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-04T18:10:47+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.452Y-5.3157
X5.6795Y-5.3157
T2
X4.2224Y-5.437
X4.4902Y-5.437
T0
M30
